remote_theme: "mmistakes/minimal-mistakes@4.22.0"
show_downloads: false
plugins:
  - jekyll-include-cache

minimal_mistakes_skin    : "default"

url              : "https://el-hult.github.io"
locale           : "en-US"

github: [metadata]

highlighter: rouge

author           : 
  name: "Ludvig Hult"
  avatar           : "/assets/images/profile.jpg"
  bio              : "Machine Learning, AI and Healthcare. Postdoctoral researcher at Uppsala University."
  links            :
    - label: "Email"
      icon: "fas fa-envelope-square"
      url: "mailto:ludvig.hult@gmail.com"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/ludvighult"
    - label: "StackOverflow"
      icon: "fab fa-stack-overflow"
      url: "https://stackoverflow.com/users/4050510/ludvigh"
    - label: "GitHub"
      icon: "fab fa-github-square"
      url: "https://github.com/el-hult/"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mastodon.acc.sunet.se/@elhult"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: false
      related: false

encoding: "utf-8"
include:
  - _pages
